# -*- coding: utf-8 -*-
"""English -> Arabic for the two construction modules.

Terminology follows the client's own operations notes: مناقصة for a tender,
مقايسة for the bill of quantities, مستخلص for a payment certificate,
تأمين ابتدائي / نهائي for the bid and performance bonds.
"""

AR = {
    # ---- generic ----
    "Name": "الاسم", "Code": "الكود", "Reference": "المرجع", "Sequence": "الترتيب",
    "Active": "نشط", "Notes": "ملاحظات", "Description": "الوصف", "Details": "التفاصيل",
    "Date": "التاريخ", "Dates": "التواريخ", "Type": "النوع", "Status": "الحالة",
    "Amount": "المبلغ", "Cost": "التكلفة", "Client": "العميل", "Summary": "الملخص",
    "Period": "الفترة", "Reason": "السبب", "Result": "النتيجة", "Revenue": "الإيرادات",
    "Scope": "نطاق العمل", "Subject": "الموضوع", "Taxes": "الضرائب", "UOM": "الوحدة",
    "File": "الملف", "Files": "الملفات", "Document": "مستند", "Documents": "المستندات",
    "Employee": "الموظف", "Employees": "الموظفون", "Team": "الفريق",
    "Settings": "الإعدادات", "Configuration": "الإعدادات", "Dashboard": "لوحة المتابعة",
    "Schedule": "الجدول الزمني", "Checklist": "قائمة المراجعة", "Rating": "التقييم",
    "Resolution": "التسوية", "Responsible": "المسؤول", "Reported By": "أبلغ عنه",
    "Expiry Date": "تاريخ الانتهاء", "Issue Date": "تاريخ الإصدار",
    "Payment Terms": "شروط السداد", "Required": "مطلوب", "Missing": "ناقص",
    "Provided": "مُقدَّم", "Provided On": "تاريخ التقديم", "Expired": "منتهي",
    "Expires": "له تاريخ انتهاء", "Used For": "يُستخدم في", "Both": "الاثنان",
    "Opinion": "الرأي", "Decision": "القرار", "Submission": "التقديم",
    "Instrument": "أداة الضمان", "Validity": "سريان الضمان", "Stores": "المخازن",
    "Live": "جارية", "Running": "جارٍ", "Outstanding": "قائم", "Request": "طلب",
    "New Certificate": "مستخلص جديد", "Certificates": "المستخلصات",

    # ---- actions / buttons ----
    "Activate": "تفعيل", "Cancel": "إلغاء", "Confirm": "تأكيد", "Close": "إغلاق",
    "Complete": "إنهاء", "Reject": "رفض", "Approve": "اعتماد", "Revise": "مراجعة",
    "Reset": "إعادة تعيين", "Reset to Draft": "إرجاع لمسودة", "Reset to Open": "إعادة فتح",
    "Start": "بدء", "Submit": "تقديم", "Terminate": "إنهاء التعاقد", "Hold": "إيقاف",
    "Mark Done": "تعليم كمنتهٍ", "Mark Lost": "تعليم كخسارة", "Mark Paid": "تعليم كمدفوع",
    "Mark Delayed": "تعليم كمتأخر", "Mark Invoiced": "تعليم كمفوتر",
    "Mark Received": "تعليم كمستلم", "Mark Won & Create Project": "ترسية وإنشاء مشروع",
    "Start Preparation": "بدء الدراسة", "Start Inspection": "بدء الفحص",
    "Start Handover": "بدء التسليم", "Submit Bid": "تقديم العطاء",
    "Print BOQ": "طباعة المقايسة", "Create RFQ": "إنشاء طلب عرض سعر",
    "Create/Open PO": "إنشاء/فتح أمر شراء", "Create Invoice / Bill": "إنشاء فاتورة",
    "Open Invoice / Bill": "فتح الفاتورة",
    "Request Approval": "طلب موافقة الإدارة", "Approve Opening": "اعتماد فتح العملية",
    "Reject Tender": "رفض المناقصة", "Hold Project": "إيقاف المشروع",
    "Load Standard Checklist": "تحميل قائمة المستندات القياسية",
    "Re-apply company ratios": "إعادة تطبيق نسب الشركة",
    "Pricing Sheet (Excel)": "جدول التسعير (إكسل)",
    "Register Booklet Fee Payment": "تسجيل صرف ثمن الكراسة",
    "Bond Issued": "تم إصدار التأمين", "Bond Released": "تم رد التأمين",
    "Bond Forfeited": "تم مصادرة التأمين",

    # ---- states ----
    "Draft": "مسودة", "Confirmed": "مؤكد", "In Progress": "قيد التنفيذ",
    "Done": "منتهٍ", "Cancelled": "ملغي", "Completed": "مكتمل", "Approved": "معتمد",
    "Submitted": "مُقدَّم", "Rejected": "مرفوض", "Invoiced": "مفوتر", "Paid": "مدفوع",
    "Received": "مستلم", "Ordered": "تم الطلب", "Planned": "مخطط", "Delayed": "متأخر",
    "On Hold": "موقوف", "Open": "مفتوح", "Closed": "مغلق", "Won": "فائزة",
    "Lost": "خاسرة", "Revised": "مُعدَّل", "Terminated": "منتهي التعاقد",
    "Failed": "فشل", "Fail": "راسب", "Pass": "ناجح", "Conditional Pass": "ناجح بشروط",
    "Handover": "تحت التسليم", "In Handover": "تحت التسليم",
    "Waiting Approval": "بانتظار الموافقة",
    "Waiting Management Approval": "بانتظار موافقة الإدارة",
    "Rejected by Management": "مرفوضة من الإدارة",
    "Lost - Bond Not Released": "خاسرة - التأمين لم يُرد",
    "Preparing Bid": "إعداد العطاء", "RFQ Created": "تم إنشاء طلب عرض السعر",
    "Invoiced/Billed": "مفوتر", "Not Required": "غير مطلوب", "To Issue": "للإصدار",
    "Issued": "صادر", "Held by Client": "محجوز لدى العميل", "Released": "مُرد",
    "Forfeited": "مُصادر",

    # ---- tender ----
    "Tender": "مناقصة", "Tenders": "المناقصات", "Tender / Bid": "مناقصة / عطاء",
    "Tender Details": "بيانات المناقصة", "Tender Item": "بند المناقصة",
    "Tender Items": "بنود المناقصة", "Tender Engineer": "مهندس المناقصة",
    "Tender Files": "ملفات المناقصات", "Tender Name...": "اسم المناقصة...",
    "Tendering Authority / Client": "الجهة المالكة / العميل",
    "Tendering Authority Type": "نوع الجهة المالكة",
    "Authority Type": "نوع الجهة", "Authority Types": "أنواع الجهات",
    "Government Body": "جهة حكومية", "Public": "مناقصة عامة", "Private": "مناقصة محدودة",
    "Negotiated": "أمر مباشر", "Loss Reason": "سبب الخسارة",
    "Awarded Project": "المشروع بعد الترسية", "Originating Tender": "المناقصة الأصلية",
    "Submission Deadline": "موعد التسليم", 
     "Operation Duration (days)": "مدة العملية (أيام)",
    "Declared Operation Value": "القيمة المعلنة للعملية",
    "Conditions Booklet": "كراسة الشروط", "Booklet & Bond": "الكراسة والتأمين",
    "Tender Document Fee": "ثمن كراسة الشروط", "Booklet Purchased": "تم شراء الكراسة",
    "Purchase Date": "تاريخ الشراء", "Fee Payment": "سند صرف الثمن",
    "Estimated Financials": "التقديرات المالية", "Scope & Notes": "نطاق العمل والملاحظات",
    "Scope of work...": "نطاق العمل...", "Internal notes...": "ملاحظات داخلية...",
    "Deadline in 7 Days": "الموعد خلال ٧ أيام",
    "Incomplete Bid File": "ملف عطاء غير مكتمل", "Bid File": "ملف العطاء",
    "Do we bid, and on what terms?": "هل نتقدم للمناقصة، وبأي شروط؟",
    "Why is this operation not worth opening?": "لماذا لا تستحق العملية الفتح؟",

    # ---- approval ----
    "Approval Request": "طلب الفتح", "Approval Date": "تاريخ الاعتماد",
    "Approved By": "اعتمدها", "Rejection Reason": "سبب الرفض",
    "Requested Budget": "المبلغ المطلوب", "Requested Engineers": "المهندسون المطلوبون",
    "Requested from Management": "المطلوب من الإدارة",
    "Reminder Lead Time": "مهلة التذكير", "Remind Before (days)": "التذكير قبل (أيام)",
    "Tender Reminder (days)": "تذكير المناقصات (أيام)",

    # ---- bonds ----
    "Bid Bond": "التأمين الابتدائي", "Bid Bond (%)": "نسبة التأمين الابتدائي (%)",
    "Bid Bond Amount": "قيمة التأمين الابتدائي",
    "Bid Bond Required": "التأمين الابتدائي مطلوب",
    "Bid Bond Ratio (%)": "نسبة التأمين الابتدائي (%)",
    "Default Bid Bond (%)": "نسبة التأمين الابتدائي الافتراضية (%)",
    "Performance Bond": "التأمين النهائي",
    "Performance Bond (%)": "نسبة التأمين النهائي (%)",
    "Performance Bond Amount": "قيمة التأمين النهائي",
    "Performance Bond Required": "التأمين النهائي مطلوب",
    "Performance Bond Ratio (%)": "نسبة التأمين النهائي (%)",
    "Bond Status": "حالة التأمين", "Bond Reference": "رقم خطاب الضمان",
    "Bond Instrument": "نوع الضمان", "Bond Issue Date": "تاريخ إصدار الضمان",
    "Bond Expiry Date": "تاريخ انتهاء الضمان", "Bond Release Date": "تاريخ رد التأمين",
    "Bond Outstanding": "تأمين قائم", "Issuing Bank": "البنك المُصدِر",
    "Cash Deposit": "إيداع نقدي", "Certified Cheque": "شيك مقبول الدفع",
    "Letter of Guarantee": "خطاب ضمان",

    # ---- pricing ----
    "Build-up Pricing": "التسعير التراكمي", "Dry Cost": "تكلفة الخامات",
    "Operating Cost": "تكلفة التشغيل", "Base Cost": "التكلفة الأساسية",
    "Profit": "الربح", "Profit (%)": "نسبة الربح (%)", "Profit Ratio (%)": "نسبة الربح (%)",
    "Contingency": "الطوارئ", "Contingency (%)": "نسبة الطوارئ (%)",
    "Contingency Ratio (%)": "نسبة الطوارئ (%)",
    "Administration": "الإدارة", "Administration (%)": "نسبة الإدارة (%)",
    "Administration Ratio (%)": "نسبة الإدارة (%)",
    "General Expenses": "المصاريف العمومية",
    "General Expenses (%)": "نسبة المصاريف العمومية (%)",
    "General Expenses Ratio (%)": "نسبة المصاريف العمومية (%)",
    "Total Markup (%)": "إجمالي نسبة الإضافة (%)", "Markup Value": "قيمة الإضافة",
    "Price before Expenses": "السعر قبل المصاريف", "Expenses Value": "قيمة المصاريف",
    "Budget Cost Rate": "سعر التكلفة التقديري",

    # ---- BOQ ----
    "BOQ": "المقايسة", "BOQ Item": "بند المقايسة", "BOQ Items": "بنود المقايسة",
    "BOQ Line": "بند المقايسة", "BOQ Lines": "بنود المقايسة",
    "Bill of Quantities": "مقايسة", "Total BOQ Amount": "إجمالي قيمة المقايسة",
    "BOQ / Cost Control": "المقايسة وضبط التكلفة",
    "Quantity Variance": "فرق الكمية", "Variance Cost": "تكلفة الفرق",
    "Over-run": "تجاوز الكمية", "Product / Service": "المنتج / الخدمة",

    # ---- project ----
    "Project": "مشروع", "Projects": "المشاريع", "Construction Project": "مشروع مقاولات",
    "Project Details": "بيانات المشروع", "Project Manager": "مدير المشروع",
    "Site Manager": "مدير الموقع", "Project Name...": "اسم المشروع...",
    "Project File": "ملف المشروع", "Project Files": "ملفات المشاريع",
    "Project Documents": "مستندات المشروع",
    "Project Analytic Account": "الحساب التحليلي للمشروع",
    "Dates & Contract": "التواريخ والعقد", "Dates & Terms": "التواريخ والشروط",
    "Contract": "العقد", "Contract Duration (days)": "مدة العقد (أيام)",
    "Financial Summary": "الملخص المالي", "Financial Control": "الرقابة المالية",
    "Drive Folder": "مجلد Drive", "Site Warehouse": "مخزن الموقع",
    "Site Location": "موقع المخزون", "Drawings": "الرسومات",
    "Electrical Engineer": "مهندس كهرباء", "Mechanical Engineer": "مهندس ميكانيكا",
    "Logistics Manager": "مدير الحركة", "Finance Manager": "المدير المالي",
    "Finance Responsible": "المسؤول المالي", "Responsible Accountant": "المحاسب المسؤول",
    "HR Supervisor": "مشرف الموارد البشرية", "Assigned Employees": "الموظفون المكلفون",
    "Hold Reason": "سبب الإيقاف", "Held Since": "موقوف منذ",
    "Hold Approved By": "اعتمد الإيقاف", "Hold Requested By": "طلب الإيقاف",
    "Why is the site stopping, and what unblocks it?":
        "لماذا يتوقف الموقع، وما الذي يعيد تشغيله؟",
    "Initial Handover": "التسليم الابتدائي", "Final Handover": "التسليم النهائي",
    "Handover & Closure": "التسليم والإقفال", "Closure Notes": "ملاحظات الإقفال",
    "Overall Progress %": "نسبة الإنجاز الكلية %",

    # ---- profit statement ----
    "Profit Statement": "بيان الأرباح", "Cost Breakdown": "تفصيل التكلفة",
    "Raw Materials": "المواد الخام", "Salaries & Wages": "المرتبات والأجور",
    "Equipment": "المعدات", "Overheads": "المصاريف العمومية",
    "Other Expenses": "مصروفات أخرى", "Direct Purchases": "المشتريات المباشرة",
    "Subcontractor Expenses": "مصروفات مقاولي الباطن",
    "Certified Subcontractor Work": "أعمال مقاولي الباطن المعتمدة",
    "Total Certificates": "إجمالي المستخلصات", "Total Cost": "إجمالي التكلفة",
    "Net Profit": "صافي الربح", "Net Margin (%)": "نسبة صافي الربح (%)",

    # ---- billing ----
    "Billing": "المستخلصات", "RA Billing": "المستخلصات الجارية",
    "Progress Billing": "مستخلصات الإنجاز", "Certificate": "مستخلص",
    "Certificate Line": "بند المستخلص", "Certificate Lines": "بنود المستخلص",
    "Payment Certificates": "المستخلصات",
    "Construction Payment Certificate": "مستخلص أعمال",
    "Construction Certificate": "مستخلص أعمال",
    "Customer Certificate": "مستخلص عميل",
    "Subcontractor Certificate": "مستخلص مقاول باطن",
    "Customer / Subcontractor": "عميل / مقاول باطن",
    "Customer Invoices": "فواتير العملاء", "Vendor Bills": "فواتير الموردين",
    "Invoice / Vendor Bill": "الفاتورة",

    # ---- procurement ----
    "Procurement": "المشتريات", "Purchase Orders": "أوامر الشراء",
    "Purchase Lines": "بنود الشراء", "Requisitions": "طلبات التوريد",
    "Material Requisition": "طلب توريد مواد",
    "Material Requisition Line": "بند طلب التوريد",
    "Material Requisitions": "طلبات توريد المواد",
    "Material Requests": "طلبات المواد", "Materials": "المواد",
    "Preferred Vendor": "المورد المفضل", "Vendor Payment Terms": "شروط سداد المورد",
    "Related Purchase Order": "أمر الشراء المرتبط",
    "Subcontract Purchase Order": "أمر شراء مقاول الباطن",
    "RFQs & POs": "طلبات الأسعار وأوامر الشراء",
    "RFQs / Purchase Orders": "طلبات الأسعار / أوامر الشراء",
    "Subcontract": "تعاقد باطن", "Subcontracts": "مقاولو الباطن",
    "Subcontractor": "مقاول باطن", "Service Product": "منتج الخدمة",

    # ---- planning / execution ----
    "Planning": "التخطيط", "WBS Phase": "مرحلة العمل", "WBS Phases": "مراحل العمل",
    "Phase Details": "بيانات المرحلة", "Parent Phase": "المرحلة الأم",
    "Sub-phases": "المراحل الفرعية", "Work Order": "أمر شغل",
    "Work Orders": "أوامر الشغل", "Work Execution": "تنفيذ الأعمال",
    "Execution Lines": "بنود التنفيذ", "Foreman": "مشرف الموقع",
    "Construction Work Order Execution Line": "بند تنفيذ أمر الشغل",
    "Civil": "أعمال مدنية", "Structural": "أعمال إنشائية", "Electrical": "أعمال كهرباء",
    "Plumbing/MEP": "أعمال صحية وميكانيكا", "Finishing": "تشطيبات",
    "External Works": "أعمال خارجية", "Other": "أخرى",
    "Normal": "عادي", "High": "مرتفع", "Urgent": "عاجل",

    # ---- quality ----
    "Quality": "الجودة", "Quality Check": "فحص جودة", "Quality Checks": "فحوصات الجودة",
    "Quality Checklist Item": "بند قائمة فحص الجودة",
    "Inspection Details": "بيانات الفحص", "Inspector": "الفاحص",
    "Inspector & Type": "الفاحص والنوع", "Final Inspection": "الفحص النهائي",
    "Material Inspection": "فحص المواد", "Workmanship": "جودة التنفيذ",
    "Safety": "السلامة", "Corrective Action": "الإجراء التصحيحي",
    "Remarks & Corrective Action": "الملاحظات والإجراء التصحيحي",
    "Remarks...": "ملاحظات...", "Corrective actions required...": "الإجراءات التصحيحية المطلوبة...",

    # ---- expenses ----
    "Expenses": "المصروفات", "Expense Details": "بيانات المصروف",
    "Construction Expense": "مصروف مشروع", "Incurred By": "تحمَّلها",
    "Labour": "عمالة", "Material": "مواد", "Overhead": "مصاريف عمومية",

    # ---- documents ----
    "Construction Document": "مستند مشروع",
    "Construction Document Type": "نوع مستند المشاريع",
    "Document Type": "نوع المستند", "Document Types": "أنواع المستندات",
    "Required Documents": "المستندات المطلوبة",
    "Missing Documents": "المستندات الناقصة",
    "Documents Ready (%)": "اكتمال المستندات (%)",
    "Required by Default": "مطلوب افتراضياً",
    "Technical File": "الملف الفني", "Financial File": "الملف المالي",
    "Legal File": "الملف القانوني",
    "Technical File Ready": "الملف الفني مكتمل",
    "Financial File Ready": "الملف المالي مكتمل",
    "Technical Office": "المكتب الفني",
    "Technical Office Opinion": "رأي المكتب الفني",
    "Technical Office Reviewer": "مراجع المكتب الفني",
    "Technical Review Date": "تاريخ المراجعة الفنية",
    "Technical specifications, delivery instructions...":
        "المواصفات الفنية وتعليمات التسليم...",

    # ---- HR ----
    "HR Case": "حالة موارد بشرية", "HR Cases": "حالات الموارد البشرية",
    "Construction HR Case": "حالة موارد بشرية بالمشروع",
    "Human Resources": "الموارد البشرية", "Management": "الإدارة",
    "Finance": "المالية", "Appraisal": "تقييم", "Appraisals": "التقييمات",
    "Issue": "مشكلة", "Issues": "المشاكل", "Absence": "غياب", "Warning": "إنذار",
    "Poor": "ضعيف", "Below Expectations": "أقل من المتوقع", "Meets": "مطابق للتوقعات",
    "Exceeds": "أعلى من المتوقع",
    "What happened?": "ماذا حدث؟",

    # ---- app ----
    "Construction": "المقاولات",
    "Construction Dashboard": "لوحة متابعة المقاولات",
    "Amount & Approval": "المبلغ والاعتماد",

    # ---- labels Odoo derives from the field name ----
    "Ref": "المرجع", "State": "الحالة", "Category": "التصنيف", "Priority": "الأولوية",
    "Location": "الموقع", "Remarks": "ملاحظات", "Subtotal": "الإجمالي الفرعي",
    "Currency": "العملة", "Uom": "الوحدة", "Qty": "الكمية", "Line": "البند",
    "Boq": "المقايسة", "Wbs": "مرحلة العمل", "Check": "الفحص",
    "Requisition": "طلب التوريد", "Requested By": "طلبها",
    "Project Code": "كود المشروع", "Tender No.": "رقم المناقصة",
    "Tender Type": "نوع المناقصة", "Item No.": "رقم البند",
    "Certificate No.": "رقم المستخلص", "Work Type": "نوع العمل",
    "Check Type": "نوع الفحص", "Check Date": "تاريخ الفحص",
    "Is Checked": "تم فحصه", "Section Header": "عنوان قسم",
    "Scope Of Work": "نطاق العمل",

    # dates
    "Start Date": "تاريخ البدء", "End Date": "تاريخ الانتهاء",
    "Planned Start": "البدء المخطط", "Planned End": "الانتهاء المخطط",
    "Actual Start": "البدء الفعلي", "Actual End": "الانتهاء الفعلي",
    "Date Requested": "تاريخ الطلب", "Date Required": "التاريخ المطلوب",
    "Billing Date": "تاريخ المستخلص",
    "Billing Period Start": "بداية فترة المستخلص",
    "Billing Period End": "نهاية فترة المستخلص",

    # quantities
    "Planned Qty": "الكمية المخططة", "Executed Qty": "الكمية المنفذة",
    "Accepted Qty": "الكمية المقبولة", "Rejected Qty": "الكمية المرفوضة",
    "Purchased Qty": "الكمية المشتراة", "Contract Qty": "كمية العقد",
    "Current Qty": "كمية الفترة", "Prev. Qty": "الكمية السابقة",
    "Qty Requested": "الكمية المطلوبة", "Qty Approved": "الكمية المعتمدة",
    "Qty Received": "الكمية المستلمة", "Qty Cumulative": "الكمية التراكمية",
    "Qty Remaining": "الكمية المتبقية",
    "Customer Certified Qty": "الكمية المعتمدة للعميل",
    "Subcontract Certified Qty": "الكمية المعتمدة لمقاول الباطن",
    "Remaining Execution Qty": "الكمية المتبقية للتنفيذ",

    # money
    "Unit Rate": "سعر الوحدة", "Unit Cost": "تكلفة الوحدة",
    "Unit Price": "سعر الوحدة", "Cost Rate": "سعر التكلفة",
    "Bid Unit Rate": "سعر وحدة العطاء",
    "Estimated Cost Rate": "سعر التكلفة التقديري",
    "Estimated Bid Value": "قيمة العطاء التقديرية",
    "Estimated Cost": "التكلفة التقديرية", "Estimated Margin": "الهامش التقديري",
    "Estimated Margin Percent": "نسبة الهامش التقديري",
    "Contract Value": "قيمة العقد", "Total Amount": "الإجمالي",
    "Total Estimated Cost": "إجمالي التكلفة التقديرية",
    "Total Expenses": "إجمالي المصروفات", "Purchase Total": "إجمالي المشتريات",
    "Budget Cost": "التكلفة المعتمدة", "Budget Revenue": "الإيراد المعتمد",
    "Budget Margin": "الهامش المعتمد", "Budget Margin Percent": "نسبة الهامش المعتمد",
    "Actual Cost": "التكلفة الفعلية", "Planned Cost": "التكلفة المخططة",
    "Committed Cost": "التكلفة الملتزم بها", "Gross Margin": "مجمل الربح",
    "Forecast Margin": "الهامش المتوقع", "Margin": "الهامش",
    "Invoiced Revenue": "الإيرادات المفوترة",
    "Certified Revenue": "الإيرادات المعتمدة",
    "Certified Amount": "القيمة المعتمدة",
    "Certified Subcontract Cost": "تكلفة الباطن المعتمدة",
    "Billed Amount": "القيمة المفوترة", "Paid Amount": "القيمة المدفوعة",
    "Amount Remaining": "القيمة المتبقية", "Amount Earned": "القيمة المستحقة",
    "Amount Previously Billed": "المفوتر سابقاً",
    "Amount This Period": "قيمة الفترة الحالية",
    "Previous Billed": "المستخلص السابق", "Net Amount": "الصافي",
    "Net Payable": "صافي المستحق", "Other Deductions": "استقطاعات أخرى",
    "Retention %": "نسبة المحتجز %", "Retention Amount": "قيمة المحتجز",
    "Advance %": "نسبة الدفعة المقدمة", "Advance Recovery": "خصم الدفعة المقدمة",
    "Billing Type": "نوع المستخلص",

    # progress
    "% Complete": "نسبة الإنجاز %", "Progress %": "نسبة الإنجاز %",
    "Progress Percent": "نسبة الإنجاز", "Completion Percent": "نسبة الإتمام",

    # counters
    "Billing Count": "عدد المستخلصات", "Boq Count": "عدد المقايسات",
    "Wbs Count": "عدد المراحل", "Work Order Count": "عدد أوامر الشغل",
    "Subcontract Count": "عدد تعاقدات الباطن",
    "Material Requisition Count": "عدد طلبات التوريد",
    "Quality Check Count": "عدد فحوصات الجودة",
    "Expense Count": "عدد المصروفات", "Project Count": "عدد المشاريع",
    "Purchase Order Count": "عدد أوامر الشراء",
    "Vendor Bill Count": "عدد فواتير الموردين",
    "Customer Invoice Count": "عدد فواتير العملاء",

    # reminder flags
    "Reminder Submission Sent": "تم إرسال تذكير التسليم",
    "Reminder Envelope Sent": "تم إرسال تذكير فتح المظاريف",
    "Reminder Award Sent": "تم إرسال تذكير البت",

    # ---- messages shown to the user from code ----
    "Set the tendering authority before asking for approval.":
        "حدد الجهة المالكة قبل طلب الموافقة.",
    "Set the submission deadline before asking for approval.":
        "حدد موعد التسليم قبل طلب الموافقة.",
    "Only a draft tender can be sent for approval.":
        "لا تُرسل للموافقة إلا مناقصة في حالة مسودة.",
    "Only a tender waiting for approval can be approved.":
        "لا يُعتمد إلا ما هو بانتظار موافقة الإدارة.",
    "Only a tender waiting for approval can be rejected.":
        "لا يُرفض إلا ما هو بانتظار موافقة الإدارة.",
    "Only a tender the management has approved and the technical office is studying can be submitted.":
        "لا يُقدَّم العطاء إلا لمناقصة اعتمدتها الإدارة ويدرسها المكتب الفني.",
    "The booklet fee can only be spent after management has approved opening the tender.":
        "لا يُصرف ثمن الكراسة إلا بعد اعتماد الإدارة لفتح العملية.",
    "The bid bond has to be issued before the bid is submitted.":
        "يجب إصدار التأمين الابتدائي قبل تقديم العطاء.",
    "These required documents are still missing:\\n%s":
        "المستندات المطلوبة الآتية ما زالت ناقصة:\\n%s",
    "These documents have expired:\\n%s":
        "المستندات الآتية منتهية الصلاحية:\\n%s",
    "Price the tender items before submitting.":
        "سعّر بنود المناقصة قبل التقديم.",
    "Set the tender document fee first.":
        "حدد ثمن كراسة الشروط أولاً.",
    'Record the initial handover date before closing "%s".':
        'سجّل تاريخ التسليم الابتدائي قبل إقفال "%s".',
    'The performance bond of "%s" has not been released yet.':
        'التأمين النهائي لـ "%s" لم يُرد بعد.',
    '"%(project)s" still has %(count)s payment certificate(s) that are neither approved nor cancelled.':
        '"%(project)s" ما زال به %(count)s مستخلص غير معتمد وغير ملغي.',
    "Only a running project can move to handover.":
        "لا ينتقل للتسليم إلا مشروع جارٍ.",
    '"%s" already exists.': '"%s" موجود بالفعل.',

    # chatter and activity messages
    "Opening approved. Budget released: %(budget)s.":
        "تم اعتماد فتح العملية. المبلغ المفرج عنه: %(budget)s.",
    "Opening rejected. Reason: %s": "تم رفض فتح العملية. السبب: %s",
    "Approve opening of tender %s": "اعتماد فتح المناقصة %s",
    "Requested budget: %(budget)s. Submission deadline: %(deadline)s.":
        "المبلغ المطلوب: %(budget)s. موعد التسليم: %(deadline)s.",
    "Answered by management.": "تم الرد من الإدارة.",
    "Conditions booklet purchased for %s.": "تم شراء كراسة الشروط بمبلغ %s.",
    "Tender lost. Kept open until the bid bond of %s is released.":
        "خسرنا المناقصة. تبقى مفتوحة حتى يُرد التأمين الابتدائي %s.",
    "Bid bond released.": "تم رد التأمين الابتدائي.",
    "Bid bond forfeited: %s.": "تمت مصادرة التأمين الابتدائي: %s.",
    "Performance bond released.": "تم رد التأمين النهائي.",
    "Project put on hold. Reason: %s": "تم إيقاف المشروع. السبب: %s",
    "%(label)s for %(tender)s": "%(label)s لـ %(tender)s",
    "Due on %s.": "الموعد %s.",
    "Tender document fee - %s": "ثمن كراسة الشروط - %s",

    # window titles opened from code
    "Reject Tender": "رفض المناقصة",
    "Hold Project": "إيقاف المشروع",
    "Project Documents": "مستندات المشروع",
    "Tender Document Fee": "ثمن كراسة الشروط",
    "HR Cases": "حالات الموارد البشرية",
    "Only the construction management can answer a request to open an operation.":
        "لا يرد على طلب فتح العملية إلا إدارة المقاولات.",
    "Tender Document Fee For": "ثمن كراسة شروط لـ",
    "Conditions booklet fee settled by %s.": "تم سداد ثمن كراسة الشروط بالسند %s.",
    "Refresh from Tender": "تحديث من المناقصة",
    "This project did not come from a tender.": "هذا المشروع لم يأتِ من مناقصة.",
    "The tender has nothing filled in that the project is missing.":
        "لا يوجد في المناقصة بيان ناقص لدى المشروع.",
    "Refreshed from tender %s.": "تم التحديث من المناقصة %s.",
    # ---- subcontract assignment ----
    "Subcontract Item": "بند إسناد",
    "Assigned Items": "البنود المسندة",
    "Subcontract Assignments": "الإسنادات",
    "BOQ Item": "بند المقايسة",
    "BOQ Quantity": "كمية المقايسة",
    "Selling Rate": "سعر البيع",
    "Own Cost Rate": "سعر التكلفة عندنا",
    "Assigned Quantity": "الكمية المسندة",
    "Subcontractor Rate": "سعر المقاول",
    "Assigned Value": "قيمة الإسناد",
    "Assigned Cost": "تكلفة الإسناد",
    "Unassigned Quantity": "الكمية غير المسندة",
    "Over-assigned": "إسناد زائد",
    "Item Margin": "هامش البند",
    "Item Margin (%)": "هامش البند (%)",
    "Margin on Assignment": "هامش الإسناد",
    "Margin (%)": "الهامش (%)",
    "Margin after Subcontracting": "الهامش بعد الإسناد",
    "Margin after Subcontracting (%)": "الهامش بعد الإسناد (%)",
    "Certified Quantity": "الكمية المعتمدة",
    "Remaining Quantity": "الكمية المتبقية",
    "Add Unassigned BOQ Items": "إضافة بنود المقايسة غير المسندة",
    "Item": "بند",
    "Progress (%)": "نسبة الإنجاز (%)",
    "Completed Quantity": "الكمية المنجزة",
    "Quantity to Certify": "الكمية المستحقة",
    "Value to Certify": "القيمة المستحقة",
    "Subcontractor Certificate": "مستخلص مقاول باطن",
    "Certificate - %s": "مستخلص - %s",
    "Nothing new to certify. Set the progress on the assigned items first.":
        "لا يوجد جديد للاستخلاص. حدد نسبة الإنجاز على البنود المسندة أولاً.",
    "Certify Progress": "استخلاص الإنجاز",
    "Blank Certificate": "مستخلص فارغ",
    "New Certificate": "مستخلص فارغ",
    "Done In-house": "منجز ذاتياً",
    "Done by Subcontractors": "منجز بالباطن",
    "In-house Scope": "نصيب التنفيذ الذاتي",
    "Still Available": "المتاح للتخطيط",
    # ---- validation messages from the base module ----
    "Accepted quantity cannot exceed executed quantity.":
        "الكمية المقبولة لا تتجاوز الكمية المنفذة.",
    "Accepted quantity exceeds the BOQ contract quantity.":
        "الكمية المقبولة تتجاوز كمية المقايسة التعاقدية.",
    "Work order quantities cannot be negative.":
        "كميات أمر الشغل لا تكون بالسالب.",
    "Cumulative quantity cannot exceed contract quantity.":
        "الكمية التراكمية لا تتجاوز الكمية التعاقدية.",
    "Contract value cannot be negative.": "قيمة العقد لا تكون بالسالب.",
    "Net payable cannot be negative.": "صافي المستحق لا يكون بالسالب.",
    "End date cannot be earlier than start date.":
        "تاريخ الانتهاء لا يسبق تاريخ البدء.",
    "Billing period end cannot be earlier than start.":
        "نهاية فترة المستخلص لا تسبق بدايتها.",
    "Required date cannot be earlier than request date.":
        "التاريخ المطلوب لا يسبق تاريخ الطلب.",
    "Submission deadline cannot be earlier than the issue date.":
        "موعد التسليم لا يسبق تاريخ الإصدار.",

    "Add at least one material line before submitting.":
        "أضف بند مواد واحداً على الأقل قبل التقديم.",
    "Add at least one priced item before submitting the tender.":
        "أضف بنداً مسعّراً واحداً على الأقل قبل تقديم المناقصة.",
    "Add certificate lines before submitting.":
        "أضف بنود المستخلص قبل التقديم.",
    "Add tender items before converting to a project.":
        "أضف بنود المناقصة قبل تحويلها إلى مشروع.",
    "This tender has already been converted into a project.":
        "هذه المناقصة تم تحويلها إلى مشروع بالفعل.",
    "Approve the certificate first.": "اعتمد المستخلص أولاً.",
    "The requisition must be approved before creating an RFQ.":
        "يجب اعتماد طلب التوريد قبل إنشاء طلب عرض السعر.",
    "Select a preferred vendor first.": "اختر المورد المفضل أولاً.",
    "Select a service product for the subcontract.":
        "اختر منتج الخدمة الخاص بتعاقد الباطن.",
    "No approved product quantities are available.":
        "لا توجد كميات معتمدة متاحة.",
    "Set the service product on the subcontract, or on these BOQ ":
        "حدد منتج الخدمة على تعاقد الباطن، أو على بنود المقايسة الآتية ",

    # report and record labels built in code
    "%s - Initial BOQ": "%s - المقايسة المبدئية",
    "%s Certificate": "مستخلص %s",
    "Subcontractor Certificates": "مستخلصات مقاولي الباطن",
    "Retention Deduction": "خصم المحتجز",
    "Pricing": "التسعير",
    "No.": "م",
    "Quantity": "الكمية",
    "Unit": "الوحدة",
    "Total": "الإجمالي",
    "Profit %": "نسبة الربح %",
    "Contingency %": "نسبة الطوارئ %",
    "Administration %": "نسبة الإدارة %",
    "Expenses %": "نسبة المصاريف %",
    # ---- labour and shifts ----
    "Labour Type": "نوع العمالة",
    "Labour Types": "أنواع العمالة",
    "Labour Requirement": "تقدير العمالة",
    "Labour & Shifts": "العمالة والورديات",
    "Trade": "الحرفة",
    "Crew Size": "عدد أفراد الوردية",
    "Shifts": "عدد الورديات",
    "Man-shifts": "ورديات الأفراد",
    "Hours per Shift": "ساعات الوردية",
    "Total Hours": "إجمالي الساعات",
    "Rate per Person / Shift": "أجر الفرد للوردية",
    "Default Shift Rate": "أجر الوردية الافتراضي",
    "Estimated Cost": "التكلفة التقديرية",
    "Estimated Labour Cost": "تكلفة العمالة التقديرية",
    "Actual Labour Cost": "تكلفة العمالة الفعلية",
    "Labour Left to Spend": "المتبقي من موازنة العمالة",
    "Operating Cost in Prices": "تكلفة التشغيل داخل الأسعار",
    "Labour Headroom": "فائض موازنة العمالة",
    "Labour Headroom (%)": "فائض موازنة العمالة (%)",
    "Labour Over Budget": "العمالة تتجاوز الموازنة",
    "Review": "المراجعة",
    "Effort": "المجهود",
    "Site Foreman": "مشرف موقع",
    "Mason": "بنّاء",
    "Steel Fixer": "حدّاد تسليح",
    "Carpenter": "نجار مسلح",
    "Electrician": "كهربائي",
    "Plumber": "سبّاك",
    "Finishing Worker": "عامل تشطيبات",
    "Helper": "مساعد",
    "Equipment Operator": "مشغّل معدة",
    "Driver": "سائق",
    "In-house Work at Cost": "قيمة التنفيذ الذاتي بالتكلفة",
    "In-house Cost Variance": "فرق تكلفة التنفيذ الذاتي",
    "In-house Execution Control": "رقابة التنفيذ الذاتي",
    "Earned Cost": "التكلفة المكتسبة",
    "Cost Variance": "فرق التكلفة",
    "Actual Unit Cost": "تكلفة الوحدة الفعلية",
    "Purchases": "المشتريات",
    "Labour": "العمالة",
    "Other Costs": "تكاليف أخرى",
    "In-house Actual Cost": "التكلفة الفعلية للتنفيذ الذاتي",
    "Work Order": "أمر الشغل",
    "Expected Cost": "التكلفة المتوقعة",
    "Expected Margin": "الهامش المتوقع",
    "Expected Margin (%)": "الهامش المتوقع (%)",
    "Forecast Cost at Completion": "التكلفة المتوقعة عند الإتمام",
    "Forecast Margin": "الربح المتوقع",
    "Forecast at Completion": "التوقع عند الإتمام",
    "Traced to Work Orders": "المنسوب لأوامر الشغل",
    "Not Traced to an Item": "غير منسوب لبند",
    "Cost Traceability": "تتبّع التكلفة",
    "Subcontractor Cost Counted Twice": "تكلفة الباطن محسوبة مرتين",
    "Technical Envelope Opening": "موعد فتح المظاريف الفني",
    "Financial Award Decision": "موعد البت المالي",
    "Technical envelope opening": "فتح المظاريف الفني",
    "Financial award decision": "البت المالي",
    "Tax (%)": "نسبة الضريبة (%)",
    "Tax Value": "قيمة الضريبة",
    "Price before Tax": "السعر قبل الضريبة",
    "Performance Bond": "التأمين النهائي",
    "What is left, and what was agreed on handover...":
        "ما تبقى، وما تم الاتفاق عليه عند التسليم...",
    "Administrative Handover": "التسليم الإداري",
    "Headroom to Cost": "المتاح حتى سعر التكلفة",
    'The subcontractor rate for "%(item)s" is %(rate)s, above the %(budget)s the item was priced to cost.\nEither negotiate the rate down, or correct the item cost in the bill of quantities if the estimate was wrong.':
        'سعر المقاول لـ "%(item)s" هو %(rate)s، وهو أعلى من %(budget)s التي سُعّر البند على أساسها.\nإما أن تفاوض على خفض السعر، أو تصحح تكلفة البند في المقايسة إذا كان التقدير خاطئاً.',
}
